platanus/la-guia

- contenido/cultura.md
@blackjid  @agustinf @ldlsegovia Acá agregué lo que hablamos el lunes. Hice una modificación sobre la idea de dejar la columna "En proceso" vacía. Habíamos hablado de dividir la tarjeta en lo terminado (a CodeReview) y lo pendiente (a Listo para Trabajar). Propongo que sea la misma tarjeta la que se mueva de CodeReview a Listo para Trabajar en caso de que queden cosas pendientes. Lo hice así porque creo que en los comentarios puede haber un historial importante que vale la pena mantener vivo. ¿qué opinan?
> feat(culture): describe Platanus Trello columns

- style/config/.scss-lint.yml
This was expected to work like this but was wrongly configured. Currently it does not allow for shorthands like:
```css
margin: 4px 5px 3px 10px;
```
> fix(): allow shorthands with 4 values

- style/config/tslint.json
no-unused-new does not exist and was crashing vscode (https://github.com/Microsoft/vscode-tslint/issues/66)
> fix(): remove unnecesary rule

- style/config/.rubocop.yml
Ruby ahora soporta **keyword arguments**, con lo cual no es tan raro tener algo como:
`def foo(_amount = nil, field: nil, fixed: false, factor: 1, modifier: :none, missing: 1)`
Entiendo que esta regla se aplique a:
`def foo(_amount, _field, _fixed, _factor, _modifier, _missing)`
Pero entorpece el uso del los **keyword arguments**...
> Disable Metrics/ParameterLists

- style/config/.rubocop.yml
Enable `Style/Not` cop to force the use of `!` instead of `not`
Esto nace de la conversacion en este PR
https://github.com/platanus/amigosecreto-rails/pull/79#pullrequestreview-7545856
> use `!` insdead of `not`

- style/config/.rubocop.yml
Me pasó esto:
Se queja de que los bloques tienen muchas líneas. Me parece que esto no tiene sentido porque cuando el bloque está dentro de un método, se queja también `Metrics/MethodLength` y cuando el bloque está fuera de un método generalmente lo usamos en DSLs y estos suelen ser bloques de definición con muchas líneas. Como es el caso de los `describe` de Rspec.
> @blackjid Creo que esto me empezó a pasar cuando instalé Rubocop 0.45
> feat(rubocop): disable Metrics/BlockLength

- style/config/.rubocop.yml
https://trello.com/c/rZnZtjTd/423-2p-16v-actualizar-las-reglas-para-ser-compatibles-con-rubocop-047
I was manually updating rubocop rules but then I was enlightened: as https://rubocop.readthedocs.io/en/latest/configuration/#updating-the-configuration-file says, the very nice gem `mry` updates a rubocop rules file to a target version automatically.
I checked the changes and it looks good. I can confirm that works with rubocop `v0.49.1`
> task(rubocop): update ruby style file to work with rubocop v0.49+

- tools/git.md
- Agrega nuevos tipos de commits para la parte de `git`
- Arregla un enlace roto a la referencia de donde nos inspiramos en los estilos de commits
> Git commit types

- style/config/.eslintrc.json
120 caracteres para mantener el estilo que tiene nuestro `tslint.json`
> style(eslintrc): set max line length to 120 chars

- style/config/.rubocop.yml
- style/config/README.md
Se actualizan las reglas de ruby a ~`rubocop v 0.61.1`~ `rubocop v0.65`
- Se actualiza `.rubocop.yml` usando [mry](https://github.com/pocke/mry)
- Se agregan nuevos Cops recomendados (😱 ). La idea es que los veamos entre todos y decidamos en este PR.
- Se actualizan cops obsoletos que `mry` no pudo migrar a sus equivalentes
> Rubocop update 0.65

- style/config/.rubocop.yml
- Había una regla que se me pasó actualizar (`Style/FlipFlop` -> `Lint/FlipFlop`)
- Probablemente el mono no estaba funcionando porque en algún momento cambiaron el comportamiento de la herencia de las configuraciones y al hacer `Include` se estaban excluyendo todos los archivos que no estaban ahí (https://github.com/rubocop-hq/rubocop/blob/master/manual/configuration.md#inheritance)
> Fix rubocop 0.65

- style/config/.eslintrc.json
- Cambia la versión de javascript (para permitir el uso de object spread)
- Agrega las reglas de vue para que no muera al encontrarse con `<template>`
> Update eslint rules

- style/config/.rubocop.yml
Ya que el comportamiento de rubocop es usar las reglas por defecto y sólo re-escribir las que estén definidas en el `.rubocop.yml` que se le especifique al hacer lint (https://rubocop.readthedocs.io/en/latest/configuration/#defaults), un montón de reglas que estaban definidas eran redundantes lo que, aparte de hacer más largo el archivo de reglas, hace que mantener este archivo sea mucho más difícil.
En este PR se eliminan la mayoría de las reglas redundantes que encontré. Las que siguen en este archivo están porque:
- O se me pasó
- O la regla definida en el estilo por defecto incluye alguna opción que no tiene un equivalente definido en nuestras reglas y por lo tanto no me queda claro si el comportamiento es igual.
- O la regla define una opción diferente a nuestras reglas (está …
> chore(rubocop): replace redundant rules

- SUMMARY.md
- clients/product-owner.md
Hasta ahora no tenemos una guía para el product owner, y por lo general somos bien críticos de su trabajo. La idea de este PR es poder compartir con los nuevos PO lo que se espera de ellos, y nuestra forma general de trabajo en el día a día.
Lo que escribí es un primer draft, así que quedo atento a comentarios e ideas de modificaciones.
> feat(product-owner): add product owner guide

- tools/git.md
Este PR agrega reglas para la parte de "contexto" de los mensajes de commit y un ejemplo de las mismas reglas.
Sobre todo cuando se trabaja en una pieza de software grande que incorpora más de un sistema (por ejemplo una app rail con el frontend SPA en el mismo repo) es muy útil agregar mas información al contexto para saber específicamente qué parte del código se modificó.
La propuesta es que los mensajes de commits sean de la siguiente forma:
```
type(context.component):message
^         ^
|         Nombre tal cual aparece en el código el componente afectado (opcional)
|   
Subsistema o funcionalidad que implementa o afecta el commit
```
La idea es que el `context` se escriba usando `kebab-case` y se separe del `component` usando un punto, entendiendo que en la gran mayoría de los …
> feat(git): add rules for commit contexts and a commit example

- code/style.md
- style/config/.rubocop.yml
Desde hace un tiempo agregamos este cop al proyecto Ksec para evitar que por agregar un foco en un spec (p.ej `fit`), la suite de tests pasara haciendo 1 solo test en vez de los ~1500.
Hemos estado usando este cop y hemos ido puliendo la configuración para adaptarse al estilo que tenemos en platanus. Hasta ahora creo que ha sido una buena experiencia: 
- ya no se nos pasan los `fit`
-  ayuda como guía a la hora de hacer specs 
- ayuda a mantener un estilo similar entre todos los specs (por ejemplo un salto de línea después del último `let`, que los `context` comiencen con `when...`, etc.
- Se agrega `rubocop-rspec` como dependencia al `.rubocop` que corre el mono
- Se agrega `rubocop-rspoc` como gema requerida para correr los linters en la parte de estilos
> Rubocop rspec

- style/config/.eslintrc.json
Se agrega -1 como magic-number ignorado.
La razón es por funciones de JS que entregan -1 como resultado deseado como por ejemplo:
`Array.indexOf(element) === -1` cuando el elemento no está en el array o
`sort((a, b) => a > b ? 1 : -1)` al ordenar
> feat(eslint): add -1 as ignored magic number

- code/css.md
Se añade un resumen muy básico y resumido de cómo usamos CSS en Platanus. Ojala que de aquí salgan más modificaciones y convenciones que no añadí ahora, y que algún dev que ame el front y este motivado se anime a añadir en futuras prs (*wink wink* @gmq @ReneMoraales ).
> feat(css): add basic css guide

- code/style.md
Rubocop-rspec added a rubocop latest version installation on their [1.36.0](https://github.com/rubocop-hq/rubocop-rspec/compare/v1.35.0...v1.36.0) release ([in this commit](https://github.com/rubocop-hq/rubocop-rspec/commit/65cc815f844c0a92a477407a36d1ccee8bc5210e)). This overrides rubocop version 0.65.0 which is specified in this guide to avoid rule name changes. To avoid the override, specify rubocop-rspec version 1.35.0.
> fix(code-style): add rubocop-rspec version specification

- setup/local/linters.md
`shinnn.stylelint` ya no existe, se reemplaza por el plugin de vscode/stylelint con más downloads
> fix(linters): change vscode stylelint link

- style/config/tslint.json
Encuentro que la regla de `align arguments` es muy molesta para `Typescript`
por ejemplo, si se usa una función como `setTimeout`
Esto se considera incorrecto
```
window.setTimeout(() => {
...
}, TIMEOUT_TIME);
```
y hay que hacerlo así:
```
window.setTimeout(() => {
...
},                TIMEOUT_TIME);
```
La otra opción sería (igual de mala):
```
window.setTimeout(
() => {
...
}, 
TIMEOUT_TIME);
```
Lo que me parece muy molesto. Todos los demás align hacen sentido, pero en typescript alinear los argumentos de una función, con callbacks y promesas de por medio, me parece muy feo a la vista.
> feat(tslint): remove displeasing rule

- style/config/.eslintrc.json
Se agregan reglas para facilitar el uso de tailwind:
- Se desactiva el máximo de largo para las lineas que empiezan con "class"
- Se desactiva la regla dentro de templates de vue si son atributos de html
- Se aumenta el máximo de largo a 120 dentro de los componentes de Vue para que quede igual que el javascript normal.
> Length rules

- SUMMARY.md
- stack/ruby/rails/README.md
- stack/ruby/rails/data_migrate.md
Se agrega sección de data migrate
- Se explica por qué usar `rake db:migrate:with_data`
- También, aunque no es algo particular de la gema, se explican posibles problemas que pueden haber al manipular data en migraciones y como se podrían mitigar
Closes #134
> docs(rails): add data migrate section

- setup/local/linters.md
Se actualiza la sección considerando que ahora las reglas y versiones están indicadas en el proyecto
- Se saca la sección con instrucciones de instalación global de los linters
- Se saca todo lo relacionado a atom, rubymine y Typescript
- Se advierte sobre cambios breaking entre versiones de rubocop
- Se agregan un par de tips
- Se cambia link de ruby-rubocop para que lleve al marketplace
- Se agrega una sección para Vim
- Se agrega una solución para problema de ruby-rubocop en vscode cuando hay un `~/.rubocop.yml`
Closes #169
> docs(linters): update linters info

- stack/ruby/rails/shrine.md
Se agregan links a partes útiles de la sección de testing de la guía de Shrine
> docs(shrine): add testing links

- stack/ruby/rails/activeadmin.md
- stack/ruby/rails/shrine.md
Se agregan dos secciones a la página de active admin:
- Como agregar link de download de un archivo. Se agrega link a la sección de Shrine, y en la sección de shrine se linkea a esta sección
- Filtros custom con ransack. Links a los docs, a los matches y a la sección de asociaciones. Se pone ejemplo simple
> Aa sections

- stack/ruby/rails/activeadmin.md
- stack/ruby/rails/shrine.md
Se había agregado un `<a>` con un nombre custom a una sección de AA para poder acceder a ella mediante un link en la sección de Shrine, pero por alguna razón en gitbook no se rendereó es `<a>`. Se hace el link usando el nombre autogenerado a partid del contenido del header
> fix(shrine): use autogenerated id for aa anchor link

- cultura.md
Se cambia el link al blog actual. Se elimina link roto a la guía del blog (ya no existe)
> docs(cultura): update blog link

- SUMMARY.md
El link de homebrew en SUMMARY apuntaba a node, cambiar a `setup/local/homebrew`
> fix(SUMMARY): fix homebrew link

- jobs/README.md
Con @hidalgoegz escribimos [un post](https://plata.news/blog/recursos-de-aprendizaje-101/) con recursos de aprendizaje para gente que quiere postular, pero quiere aprender un poco de nuestro stack antes (o gente que quiere aprender a programar en general).
Este PR agrega el link a la sección de trainees en la guía
> feat(jobs): add link to learning resources on trainees page

- SUMMARY.md
- setup/proyectos/README.md
En el pr anterior #183 se agregó la sección de S3 a la parte de setup, pero faltó agregarlo al summary para que aparezca en el sidebar y en el readme de la sección
> fix(): add missing s3 links

- SUMMARY.md
- setup/local/README.md
La guía de windows no aparece en el sitio y creo que es porque faltaba el link.
> fix(): add missing windows link

- setup/local/tecnologias/ruby.md
- Se agrega como paso previo a la instalacion de ruby con rvm, sacar todo lo relacionado a este manager porque queda la escoba al tener ambos.
- Se dan opciones de como agregar el init a la shell
- Se agrega una pista de un posible error (bien recurrente) de tener mal configurado el PATH (creo que deberiamos tener una seccion explicando qué es el PATH en el mac y cómo tenerlo bien configurado, pero eso lo dejamos para otro PR).
- Sacamos lo instalar versiones de ruby con ruby-build y dejamos solo las instrucciones para hacerlo con rbenv. De todas formas dejamos el link a ruby-build por si alguien quiere usar ese plugin para instalar sus versiones de ruby.
- Pusimos el warning de instalar cosas con sudo.
> feat(tecnologias/ruby): update ruby installation instructions

- SUMMARY.md
- setup/local/herramientas/ide/visual-studio-code.md
- setup/proyectos/README.md
- setup/proyectos/getting-started.md
- setup/proyectos/git.md
- Se cambia la sección de extensiones de VSCode. Se agregan/sacan/cambian varias extensiones y se agregan links
- Se agrega sección de Getting Started al setup de proyectos. Tiene los pasos de setup de la primera vez que se corre, y cosas en que fijarse/que hacer para veces siguientes que se quiera correr
- De las extensiones saqué las de linters, ya que hay una página aparte dedicada a ellos. Puse un link a esa al final
- Dividí las extensiones en relacionadas al stack y auxiliares, para darle algo de orden. No se si es la mejor separación, abierto a sugerencias ahí también
- Para headwind copié y pegué lo que estaba en [tailwind](https://github.com/platanus/la-guia/blob/master/stack/css/tailwind.md#recursos-%C3%BAtiles)
- En la parte de git, hay un link para explicar rebase que no es el …
> Setup improvements

- setup/proyectos/getting-started.md
En #215 se agregó una sección de Getting Started del setup de un proyecto.
Por alguna razón, lo que se agregó se ve distinto en la guía a lo que se ve al levantar en local con `gitbook serve`. Específicamente, en la guía las hints no se ven anidadas e interfieran con la enumeración y estilo de los elementos siguientes de la lista:
*El bin/rails c debería ser otro elemento de la lista, como el bundle exec guard*
Este PR solo se cambia la indentación de los textos de los hints para que queden anidados. En local esto hace que se vean mal, como un bloque de código dentro de un hint:
Pero como en la guía se ve distinto, quizás ahí se soluciona, no tengo como probar sin subirlo 🤷‍♂️
> fix(project-getting-started): fix hint indentation

- setup/proyectos/getting-started.md
En #215 se agregó una sección de Getting Started del setup de un proyecto.
Por alguna razón, lo que se agregó se ve distinto en la guía a lo que se ve al levantar en local con `gitbook serve`. Específicamente, en la guía las hints no se ven anidadas e interfieran con la enumeración y estilo de los elementos siguientes de la lista:
*El bin/rails c debería ser otro elemento de la lista, como el bundle exec guard*
En #216 se probó cambiando indentación, pero no funcionó, se sigue viendo mal. En este pr se reemplazan los hints anidados por guiones no más
> fix(project-getting-started): replace nested hints with hyphens

- README.md
The url was not working, it was redirecting me to a github 404, because it had a tilde in the "the-guia" 🙄
> docs(readme): fix typo to contributors url

- deployment/browser-node.md
Se actualiza la guía sobre cómo publicar paquetes en NPM. 
También se agregan distintos detalles y secciones para tener en consideración cuando se crea un paquete, como la creación del repositorio, la definición del `package.json`, las dependencias necesarias, cómo crear comandos por consola y la sintaxis de exports. 
La guía anterior mencionaba que se debía dar acceso de owner al paquete al usuario de [Platanus](https://www.npmjs.com/org/platanus) pero eso no funciona. Se cambió por dar acceso de owner al usuario [Platanus-owner](https://www.npmjs.com/~platanus-owner), pero no sé si cumple la misma función.
> feat(browser-node): update guide and add more details
