platanus/la-guia

- contenido/angular.md
- contenido/bower.md
- contenido/ionic.md
- contenido/karma.md
- contenido/rails.md
- contenido/ruby.md
@agustinf agrego :earth_americas: en las secciones existentes. Los links a repos de github nada más?
> feat(): add :earth_americas: icon to section titles

- README.md
- contenido/trello.md
> Adds project management description

- contenido/activeadmin.md
* `has_and_belongs_to_many` with `select2`
* Filter by multiple values
> Activeadmin

- contenido/blog.md
- contenido/cultura.md
Movi y actualize la guia del blog, desde el antiguo y querido guides.
> feat(blog): adds blog section

- code/angular.md
Agrego tema de upload de archivos
> feat(angular): upload files

- SUMMARY.md
- code/angular.md
- code/ionic.md
- code/rails.md
- deployment/rails.md
Este PR a agrega una sección **getting started** y una **deployment* a la guia de Rails.
Esto viene de la mano con el trabajo hecho en 
- platanus/potassium#27
- platanus/potassium#36
- platanus/potassium#39
- platanus/potassium#40
> Update rails guide with heroku and new potassium commands

- cultura/sesiones.md
Ojalá todos los @platanus/developers lean esto y comenten si están de acuerdo y/o si falta algo..
> feat(cultura): add 'sesiones'

- code/style.md
@blackjid @arturopuente @amosrivera les parece así el formato de la sección de estilos?
> feat(code): add style section

- style/config/tslint.json
Estos son los posibles valores: https://github.com/palantir/tslint#core-rules
> feat(): revise and declare all relevant rules

- code/rails.md
How to work with environmental varibles in our projects
> environmental variables

- code/project-configuration.md
@blackjid me podrías ayudar con lo que está con `***`? No estoy seguro de esos procesos, gracias 😃
> docs(): add project configuration guide

- SUMMARY.md
- tools/environment.md
Hice este articulo para la era post-boxen
A ver si alguien se atreve a seguirlo y dar feedback.
Este es el link del branch publicado para mas facil lectura https://la-guia.platan.us/v/environment/tools/environment.html
> Adds environment setup

- code/ionic.md
Este PR actualiza la guía con los acuerdos que llegamos en el último ConclaDev de mobile.
> task(Ionic): add mobile app manifesto

- SUMMARY.md
- jobs/internship.md
Se agrega nueva sección "Trabajos" y subsección "Práctica".
> feat(jobs): add internship

- jobs/internship.md
Se veía mal como estaba formateado antes. Ahora debiera quedar mejor.
> fix(internship): modalities formatting

- style/config/.stylelintrc.json
- Se saca regla deprecada (https://github.com/stylelint/stylelint/issues/2227)
- Se actualiza nombre de regla para ids https://github.com/stylelint/stylelint/issues/2528
> Stylelint update

- tools/trello.md
Eliminar columna "Lo siguiente" de la guía.
> feat(trello): delete next column

- code/rails.md
Se cambia `fecth` por `fetch`.
> fix(rails): fix typo

- SUMMARY.md
- cultura/lunch.md
Se agrega una pequeña explicación de cómo funciona el almuerzo.
> feat(lunch): add lunch page

- INTRO.md
- SUMMARY.md
- tools/atom.md
- tools/visual-studio-code.md
Se elimina Atom y se agrega Visual Studio Code. Closes #104.
> Add vscode page and remove atom

- tools/git.md
> feat(git): add link to rebase explanation

- cultura/lunch.md
Se agrega explicación de compra/venta a diferentes montos.
> chore(lunch): update lunch page with market description

- SUMMARY.md
- stack/ruby/rails/README.md
- stack/ruby/rails/shrine.md
> feat(stack/rails): add shrine section

- deployment/google-play.md
- Se ordena un poco la info y se añaden links a la documentación oficinal.
> fix(google-play): update info for dev and fix typos

- stack/ruby/rails/shrine.md
- Se agrega link al demo
- Se agrega nota explicitando que el `_data` es necesario en el nombre de la columna
- Se agrega explicación de Direct S3 Upload y Direct App Upload, indicando diferencia y con links a ambas
> Shrine improvements

- SUMMARY.md
- stack/ruby/rails/README.md
- stack/ruby/rails/strong_migrations.md
> feat(stack/ruby): add strong migrations

- stack/css/tailwind.md
Se agregan instrucciones para que Headwind detecte clases de helpers de rails
> docs(tailwind): add quoted info in Headwind useful resource

- setup/proyectos/expo.md
- stack/mobile/README.md
- stack/mobile/expo.md
- stack/mobile/react-navigation.md
- stack/mobile/redux.md
- stack/mobile/resources.md
- stack/mobile/styling.md
Agrega una primera versión de desarrollo movil con React Native. Más que la estructura propuesta para las secciones (Porque?, Como?, ...) seguí la estructura de la sección de Ruby y Rails.
Closes #132
> feat(mobile): add mobile section

- SUMMARY.md
- setup/proyectos/README.md
- stack/README.md
Agregar links faltantes en sidebar e index de cada seccion
> feat(RN): add required links

- setup/local/windows.md
Recién tuve que reinstalar windows asi que le agregué un par de cosas que me pasaron y otras que @sleivav sugirió.
> Update Windows Guide

- setup/local/tecnologias/ruby.md
> feat(setup/local/tecnologias/ruby): add linux setup

- SUMMARY.md
Tecnologías no estaba en la barra lateral, ahora se agrega.
> feat(summary): add link to tecnologías in summary

- setup/local/tecnologias/docker.md
Link a la instalación de Docker para los dos tipos de Mac
> feat(docker/mac): Docker instructions for mac

- setup/local/tecnologias/ruby.md
> update rbenv for linux and windows.

- stack/ruby/rails/activeadmin.md
Se agregó una sección de la guía que enseña a utilizar vue en AA.
> feat(vue-AA): add instructions to use vue on AA

- setup/local/herramientas/ide/visual-studio-code.md
- setup/local/herramientas/linters.md
- setup/proyectos/getting-started.md
Algunos updates a secciones relacionadas al onboarding para nuevos devs
> Onboarding pages changes
